module.exports = {
  darkMode: "class",
  purge: ["./**/*.tsx", "./public/index.html"],
  theme: {
    maxWidth: {
      0: "0rem",
      none: "none",
      xs: "20rem",
      sm: "24rem",
      md: "28rem",
      lg: "32rem",
      xl: "36rem",
      "2xl": "42rem",
      "3xl": "48rem",
      "4xl": "56rem",
      "5xl": "64rem",
      "6xl": "72rem",
      "7xl": "80rem",
      full: "100%",
      min: "min-content",
      max: "max-content",
      prose: "65ch",
      screen: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
    },
    fontFamily: {
      sans: ["Poppins", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
      mono: ["Menlo", "Monaco", "Courier New", "monospace"],
    },
    fontSize: {
      tiny: "0.625rem",
      xs: ".75rem",
      sm: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    colors: {
      button: "var(--color-button-text)",
      transparent: "transparent",
      default: "red",
      white: "white",
      primary: {
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
      secondary: {
        DEFAULT: "var(--color-secondary)",
      },
      accent: {
        DEFAULT: "var(--color-accent)",
        hover: "var(--color-accent-hover)",
        disabled: "var(--color-accent-disabled)",
        glow: "var(--color-accent-glow)",
      },
    },
    spacing: {
      0: "0px",
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
      5: "25px",
      6: "30px",
      7: "60px",
      8: "75px",
      9: "80px",
      10: "120px",
      24: "24rem",
      100: "100px",
      200: "200px",
      320: "320px",
      300: "350px",
      400: "400px",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0px",
    },
    boxShadow: {
      accent: "var(--shadow-accent)",
      1: "0px 4px 14px rgba(0, 0, 0, 0.4)",
    },
    extend: {
      borderRadius: {
        0: "0px",
        5: "5px",
        8: "8px",
        15: "15px",
      },
      outline: {
        "no-chrome": "none",
      },
    },
  },
  variants: {
    backgroundColor: ({ after }) => after(["disabled"]),
    textColor: ({ after }) => after(["disabled"]),
    extend: {
      borderWidth: ["last"],
    },
  },
  plugins: [require("tailwind-scrollbar"), require("@tailwindcss/line-clamp"), require("@tailwindcss/forms")],
};
